apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunder-backend-deployment
  labels:
    app: thunder-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thunder-backend
  template:
    metadata:
      labels:
        app: thunder-backend
    spec:
      containers:
      - name: flask-app
        image: 182719847108.dkr.ecr.us-east-1.amazonaws.com/thunder-studio-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: db-secret
