apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: "terraform-ccf92a7bdb44b3633d5601f8b2.cqvwymqak61x.us-east-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "ThunderSecurePass123!"
  DB_NAME: "thunderstudio"
